### ISSUE TITLE
How to get the current running app to the foreground when a new instance is opened?

### ISSUE THREAD

**Issue by ghost** [necodeIT/flutter_single_instance#2]
I am using this package to prevent launching of multiple instances of the application. But I also want to bring the current running app to the foreground when a new instance is opened. Is it possible to do it from this package?
I found another package [windows_single_instance](https://pub.dev/packages/windows_single_instance) that can be used for this purpose however it is platform dependent. I would need this to work on Windows, Linux and macOS.

Thanks in advance

**Comment by mcquenji** [comment]
This is currently not supported by this package as I don't really know how to do so

**Comment by ghost** [comment]
@mcquenji thanks for the response. This would be a really good feature, I am looking forward to it

**Comment by mcquenji** [comment]
I've pushed an implementation for this request to main ([f9e7a19](https://github.com/necodeIT/flutter_single_instance/commit/f9e7a19f34a1f3e7922cbd7a947cc907eefdc674)), though it's yet to be tested. You can try it out by using:

```yaml
dependency_overrides:
  flutter_single_instance:
    git:
      url: https://github.com/necodeIT/flutter_single_instance.git
 ```
